### ISSUE TITLE
Template variable dependant of another template variable with "Include All option" on, causes Cannot read property 'replace' of null

### ISSUE THREAD

**Issue by ghuname** [Vertamedia/clickhouse-grafana#232] opened 2020-07-10 08:53 UTC
Grafana v6.6.2 (3fa63cfc34)
ClickHouse datasource for Grafana 4.6+ 1.9.5

I have several dependant templating variables:

![image](https://user-images.githubusercontent.com/15207713/87134789-7233be80-c299-11ea-8329-9f6b6ab87a97.png)

This one works always.

![image](https://user-images.githubusercontent.com/15207713/87134856-8a0b4280-c299-11ea-9603-d1d5fb47b3d8.png)

This one for now has "Include All option" disabled, and it works always.

![image](https://user-images.githubusercontent.com/15207713/87134974-b3c46980-c299-11ea-8a57-140522163ba7.png)

This one works only if $CITY has "Include All option" disabled.

If variables are set as described above everything works. Select for CMTS looks like this:
select distinct cmts from pre_eq.pre_eq where bulkId in ('2020-07-10 00:00:00')   and crmCity in ('BJELOVAR')   FORMAT JSON

If I change $CITY variable in a way to enable "Include All option", I am getting an error: "Template variable service failed
Cannot read property 'replace' of null"

Looks like there is a problem with interpretation of the $CITY variable when "Include All option" is selected.

Database fields are of types:
	,`bulkId` DATETIME
	,`cmts` String 
	,`crmCity` Nullable(String)

Is there any workaround?

**Comment by Slach** [comment] 2020-07-10 13:53
@ghuname please upgrade clickhouse grafana plugin to latest 2.0.1 published version
https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/changelog
after fix https://github.com/Vertamedia/clickhouse-grafana/issues/169
"multiple values" variables should pass better

I try to reproduce your behavior on the latest plugin master and grafana 6.7.5

I successful deploy 3 template variables which depend on each other, second and third variable have "include all" and "multiple values" option 

only one thing I keep in mind when build queries for template variables which have "multiple values" option we should use `WHERE field IN (${template_variable_name})` without single quotes

**Comment by Slach** [comment] 2020-07-10 13:57
@ghuname please look to
https://github.com/Vertamedia/clickhouse-grafana/blob/master/docker/grafana/dashboards/mutiple_depends_variable.json
and
https://github.com/Vertamedia/clickhouse-grafana/blob/master/docker/clickhouse/init_schema.sql#L33

feel free to reopen if issue reproduce on the latest version of a plugin

**Comment by ghuname** [comment] 2020-07-13 08:34
> @ghuname please upgrade clickhouse grafana plugin to latest 2.0.1 published version
> https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/changelog
> after fix #169
> "multiple values" variables should pass better

@Slach, will 2.0.1 work with Grafana v6.6.2 (3fa63cfc34)?

**Comment by Slach** [comment] 2020-07-13 09:37
@ghuname  yes, 2.x version plugin version works with 6.6.2

**Comment by ghuname** [comment] 2020-07-14 08:59
Thanks

**Comment by ghuname** [comment] 2020-07-14 12:17
@Slach I have installed 2.0.1 version and problem is still present.
Can you please reopen this issue.

**Comment by Slach** [comment] 2020-07-14 14:48
Ok. could you share your grafana dashboard JSON and SQL schema with me (via email bloodjazman@gmail.com if data is private)?

**Comment by sundy-li** [comment] 2020-07-15 08:21
> only one thing I keep in mind when build queries for template variables which have "multiple values" option we should use WHERE field IN (${template_variable_name}) without single quotes

I just faced this problem after upgraded to the newest version. If I want to use single quotes in In ${version}, but all version variables looks like Number (actually in clickhouse it's type is String), how to solve this problem?

![image](https://user-images.githubusercontent.com/3325189/87521663-3d6ba100-c6b7-11ea-9d19-c713cf926079.png)

**Comment by Slach** [comment] 2020-07-15 10:31
@sundy-li quick workaround for you
`SELECT ... WHERE os IN ( arrayMap((x)->toString(x),${client_version}) )`

**Comment by Slach** [comment] 2020-07-16 16:31
@ghuname  could you share your grafana dashboard JSON and SQL schema with me, to help me reproduce your behavior?

**Comment by ghuname** [comment] 2020-07-22 08:04
> Ok. could you share your grafana dashboard JSON and SQL schema with me (via email [bloodjazman@gmail.com](mailto:bloodjazman@gmail.com) if data is private)?

@Slach I found the root of the problem. If query among other values return a null value, than template vars engine is confused.
The solution is to add "... and field is not null" as one of conditions.

**Comment by Slach** [comment] 2020-07-22 08:55
@ghuname ok, could you close this issue and create a new issue?
what you mean "template variable engine is confused"? do you mean something wrong with grafana UI or clickhouse-grafana replace template variable with wrong values?

**Closed** 2020-07-24 10:02 UTC
